version: '3.7'
services:
  # ------------------------------------------------------------
  # MySQL - Database
  # ------------------------------------------------------------
  mysql_dev:
    image: mysql:8.3.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql:z
